name: CI/CD Pipeline

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  # analyse:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Run ESLint
  #       run: npm run lint # Assurez-vous que le script "lint" existe dans package.json

  #     - name: Scan Dockerfile with Hadolint
  #       uses: hadolint/hadolint-action@v1.5.0 # Utiliser la version v1.5.0 de Hadolint

  #     - name: Run Semgrep
  #       uses: returntocorp/semgrep-action@v1
  #       with:
  #         config: p/ci # Utiliser la configuration de Semgrep pour le CI

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejsapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejsapp:latest

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/nodejsapp:latest

  hadolint:
    name: hadolint scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif

      - name: debug the code part 1
        if: always()
        run: |
          pwd
          ls

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3

        if: always()
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

      - name: debug the code part 2
        run: |
          pwd
          ls

  lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: checkout the code
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
